import { Router } from "express";import { pool } from "../../config/db.js";import { asyncHandler } from "../../middleware/asyncHandler.js";import { requireCustomer } from "../../middleware/customerAuth.js";import { parsePositiveId } from "../../security/validation.js";import { fail,ok,paginated } from "../../utils/apiResponse.js";
const router=Router();
router.get("/product/:productId",asyncHandler(async(req,res)=>{const id=parsePositiveId(req.params.productId),page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||20,1),100);if(!id)return fail(res,400,"Invalid product ID");const [[counts],[rowsResult]]=await Promise.all([pool.query("SELECT COUNT(*) AS total FROM reviews WHERE product_id=? AND status='approved'",[id]),pool.query(`SELECT r.id,r.rating,r.title,r.review_text,r.is_verified_purchase,r.helpful_count,r.created_at,CONCAT(u.first_name,' ',LEFT(u.last_name,1),'.') AS reviewer FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? AND r.status='approved' ORDER BY r.id DESC LIMIT ? OFFSET ?`,[id,limit,(page-1)*limit])]);return paginated(res,rowsResult,{page,limit,total:Number(counts[0].total)});}));
router.get("/:id",asyncHandler(async(req,res)=>{const id=parsePositiveId(req.params.id);if(!id)return fail(res,400,"Invalid review ID");const [[row]]=await pool.query("SELECT id,product_id,rating,title,review_text,is_verified_purchase,helpful_count,created_at FROM reviews WHERE id=? AND status='approved'",[id]);if(!row)return fail(res,404,"Review not found");return ok(res,row);}));
router.post("/",requireCustomer,asyncHandler(async(req,res)=>{const productId=parsePositiveId(req.body.product_id),rating=Number(req.body.rating),title=String(req.body.title||"").trim().slice(0,190),review=String(req.body.review_text||"").trim().slice(0,5000);if(!productId||!Number.isInteger(rating)||rating<1||rating>5||!review)return fail(res,422,"Validation failed",{review:["Product, rating from 1 to 5, and review text are required"]});const [[purchase]]=await pool.query(`SELECT oi.id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.user_id=? AND oi.product_id=? AND o.status='delivered' ORDER BY oi.id DESC LIMIT 1`,[req.user.id,productId]);try{const [result]=await pool.query("INSERT INTO reviews(user_id,product_id,order_item_id,rating,title,review_text,is_verified_purchase) VALUES (?,?,?,?,?,?,?)",[req.user.id,productId,purchase?.id||null,rating,title||null,review,Boolean(purchase)]);return ok(res,{id:result.insertId},"Review submitted for moderation",201);}catch(error){if(error.code==="ER_DUP_ENTRY")return fail(res,409,"You have already reviewed this product");throw error;}}));
router.put("/:id",requireCustomer,asyncHandler(async(req,res)=>{const id=parsePositiveId(req.params.id),rating=Number(req.body.rating),review=String(req.body.review_text||"").trim().slice(0,5000);if(!id||!Number.isInteger(rating)||rating<1||rating>5||!review)return fail(res,422,"Validation failed");const [result]=await pool.query("UPDATE reviews SET rating=?,title=?,review_text=?,status='pending' WHERE id=? AND user_id=?",[rating,String(req.body.title||"").trim().slice(0,190)||null,review,id,req.user.id]);if(!result.affectedRows)return fail(res,404,"Review not found");return ok(res,null,"Review updated and submitted for moderation");}));
router.delete("/:id",requireCustomer,asyncHandler(async(req,res)=>{const id=parsePositiveId(req.params.id);if(!id)return fail(res,400,"Invalid review ID");const [result]=await pool.query("DELETE FROM reviews WHERE id=? AND user_id=?",[id,req.user.id]);if(!result.affectedRows)return fail(res,404,"Review not found");return res.status(204).end();}));
router.post("/:id/helpful",requireCustomer,asyncHandler(async(req,res)=>{const id=parsePositiveId(req.params.id);if(!id)return fail(res,400,"Invalid review ID");const connection=await pool.getConnection();try{await connection.beginTransaction();const [insert]=await connection.query("INSERT IGNORE INTO review_helpful(review_id,user_id) SELECT id,? FROM reviews WHERE id=? AND status='approved'",[req.user.id,id]);if(!insert.affectedRows){await connection.rollback();return fail(res,409,"Review was already marked helpful or was not found");}await connection.query("UPDATE reviews SET helpful_count=helpful_count+1 WHERE id=?",[id]);await connection.commit();return ok(res,null,"Review marked helpful");}catch(error){await connection.rollback();throw error;}finally{connection.release();}}));
export default router;
