import { Router } from "express";
import { pool } from "../../config/db.js";
import { asyncHandler } from "../../middleware/asyncHandler.js";
import { requireCustomer } from "../../middleware/customerAuth.js";
import { parsePositiveId } from "../../security/validation.js";
import { ensureCart } from "../../services/cart.js";
import { fail, ok } from "../../utils/apiResponse.js";

const router=Router(); router.use(requireCustomer);
async function wishlist(queryable,userId){ await queryable.query("INSERT IGNORE INTO wishlists(user_id) VALUES (?)",[userId]); const [[row]]=await queryable.query("SELECT id FROM wishlists WHERE user_id=?",[userId]); return row; }
router.get("/",asyncHandler(async(req,res)=>{ const list=await wishlist(pool,req.user.id); const [rows]=await pool.query(`SELECT wi.id AS wishlist_item_id,p.id,p.name,p.slug,p.price,p.sale_price,p.main_image,p.stock FROM wishlist_items wi JOIN products p ON p.id=wi.product_id WHERE wi.wishlist_id=? AND p.status='Active' AND p.deleted_at IS NULL ORDER BY wi.id DESC`,[list.id]); return ok(res,rows); }));
router.post("/add",asyncHandler(async(req,res)=>{ const productId=parsePositiveId(req.body.product_id); if(!productId)return fail(res,400,"Invalid product ID"); const [[product]]=await pool.query("SELECT id FROM products WHERE id=? AND status='Active' AND deleted_at IS NULL",[productId]); if(!product)return fail(res,404,"Product not found"); const list=await wishlist(pool,req.user.id); await pool.query("INSERT IGNORE INTO wishlist_items(wishlist_id,product_id) VALUES (?,?)",[list.id,productId]); return ok(res,null,"Added to wishlist",201); }));
router.delete("/remove",asyncHandler(async(req,res)=>{ const productId=parsePositiveId(req.body.product_id ?? req.query.product_id); if(!productId)return fail(res,400,"Invalid product ID"); const list=await wishlist(pool,req.user.id); const [result]=await pool.query("DELETE FROM wishlist_items WHERE wishlist_id=? AND product_id=?",[list.id,productId]); if(!result.affectedRows)return fail(res,404,"Wishlist item not found"); return res.status(204).end(); }));
router.post("/:productId/move-to-cart",asyncHandler(async(req,res)=>{ const productId=parsePositiveId(req.params.productId); if(!productId)return fail(res,400,"Invalid product ID"); const connection=await pool.getConnection(); try{ await connection.beginTransaction(); const [[product]]=await connection.query("SELECT stock FROM products WHERE id=? AND status='Active' AND deleted_at IS NULL FOR UPDATE",[productId]); if(!product||Number(product.stock)<1){await connection.rollback();return fail(res,409,"Product is unavailable");} const list=await wishlist(connection,req.user.id); const cart=await ensureCart(connection,req.user.id); const [[existing]]=await connection.query("SELECT id,quantity FROM cart_items WHERE cart_id=? AND product_id=? AND variant_id IS NULL FOR UPDATE",[cart.id,productId]); if(Number(existing?.quantity||0)+1>Number(product.stock)){await connection.rollback();return fail(res,409,"Product stock is insufficient");} if(existing)await connection.query("UPDATE cart_items SET quantity=quantity+1 WHERE id=?",[existing.id]); else await connection.query("INSERT INTO cart_items(cart_id,product_id,quantity) VALUES (?,?,1)",[cart.id,productId]); await connection.query("DELETE FROM wishlist_items WHERE wishlist_id=? AND product_id=?",[list.id,productId]); await connection.commit(); return ok(res,null,"Moved to cart"); }catch(error){await connection.rollback();throw error;}finally{connection.release();} }));
export default router;
