export { default as api, apiErrorMessage } from "./axios";
export * from "./auth.api";
export * from "./product.api";
export * from "./category.api";
export * from "./cart.api";
export * from "./wishlist.api";
export * from "./order.api";
export * from "./payment.api";
export * from "./shipping.api";
export * from "./review.api";
export * from "./address.api";
export * from "./user.api";
export * from "./faq.api";
